[Item 32] - 제네릭과 가변인수를 함께 쓸 때는 신중하라
woowacourse-study/2023-effective-java-study pull request #6
Opened 2023-02-27 01:27 UTC by hyena0608

2023-03-04 15:54 UTC, dooboocookie approved these changes
잘 읽었습니다😀

2023-03-05 03:54 UTC, shin-mallang commented on chap05/item32/제네릭과_가변인수를_함께_쓸_때는_신중하라.md
> +덕분에 메서드를 n번 오버로딩 하지않아도 됩니다.
n번보다는, 여러번이 더 읽기 쉬울 것 같아요

2023-03-05 03:54 UTC, shin-mallang commented on chap05/item32/제네릭과_가변인수를_함께_쓸_때는_신중하라.md
> +#### **매개변수화 타입과 가변인수**
`###` 세개는 어떤가요? 네개는 너무 작아서 티가 잘 안나네요

2023-03-05 03:54 UTC, shin-mallang commented on chap05/item32/제네릭과_가변인수를_함께_쓸_때는_신중하라.md
> +먼저 제네릭과 가변인수를 같이 사용하면 타입이 불안정 할 수 있습니다.
왜 타입이 불안정 할 수 있나요?

2023-03-05 05:00 UTC, Combi153 approved these changes
어려운 개념이었을텐데 고생하셨습니다!

2023-03-05 07:07 UTC, hyena0608 commented on chap05/item32/제네릭과_가변인수를_함께_쓸_때는_신중하라.md
> +먼저 제네릭과 가변인수를 같이 사용하면 타입이 불안정 할 수 있습니다.
제네릭은 실체화 불가 타입으로 컴파일 시에 타입이 사라집니다.

```java
sampleMethod(List<String>... values) {

}
```

와 같은 메서드가 컴파일 시에 각 데이터들은 List<String>[]이 아닌 List[] 배열에 저장됩니다.
런타임 중에 List[] 배열에 다른 타입이 들어와서 형변환 에러가 발생할 수도 있기 때문이었습니다.

현재 기준으로 전체적으로 내용 수정이 이루어졌고, 간단한 예시로 설명하고 있습니다.

2023-03-05 07:07 UTC, hyena0608 commented on chap05/item32/제네릭과_가변인수를_함께_쓸_때는_신중하라.md
> +#### **매개변수화 타입과 가변인수**
반영하겠습니다 ~

2023-03-05 13:35 UTC, Ohjintaek approved these changes
발표 때도 느꼈지만 어려운 내용이었습니다. 그래도 찬찬히 보니 조금씩 이해가 되는 거 같아요!!

2023-03-05 13:35 UTC, Ohjintaek commented on chap05/item32/제네릭과_가변인수를_함께_쓸_때는_신중하라.md
> +    -  *"단점 01. RawType List는 타입에 불안전하다." 를 해결한다.
"단점 01" 앞에 *가 지워지지 않은 거 같아요

2023-03-05 13:35 UTC, Ohjintaek commented on chap05/item32/제네릭과_가변인수를_함께_쓸_때는_신중하라.md
> +예외 발생 원인은 convertBy에서 컴파일 시점에 만들어진 T\[\] 자신을 직접 반환하고*
이 문장 끝에도 *가 있어요.

2023-03-05 14:38 UTC, shin-mallang approved these changes

2023-03-05 14:38 UTC, shin-mallang requested changes
후추가 말씀해주신것만 수정하면 될거같아요

2023-03-05 19:16 UTC, hyena0608 commented on chap05/item32/제네릭과_가변인수를_함께_쓸_때는_신중하라.md
> +    -  *"단점 01. RawType List는 타입에 불안전하다." 를 해결한다.
앗 감사합니다 !!

2023-03-05 19:16 UTC, hyena0608 commented on chap05/item32/제네릭과_가변인수를_함께_쓸_때는_신중하라.md
> +예외 발생 원인은 convertBy에서 컴파일 시점에 만들어진 T\[\] 자신을 직접 반환하고*
😲 👍

2023-03-06 09:42 UTC, merged